version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    env_file:
      - tw.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: twitter-like
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - ./data/db:/var/lib/postgresql/data
