services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    env_file:
      - tw.env
    depends_on:
      - db
  db:
    image: postgres
    
    env_file:
      - tw.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
