services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:80"
    env_file:
      - tw.env
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: twitter-like
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pappol
    volumes:
      - ./data/db:/var/lib/postgresql/data
